# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardTitle', models.TextField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('uniqueNumber', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('boardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Board')),
            ],
        ),
    ]
