# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='boardDescription',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
