# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='tableID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Table'),
        ),
    ]
