# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_board_boarddescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='activeStatus',
            field=models.BooleanField(default=True),
        ),
    ]
