# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_card_activestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='activeStatus',
            field=models.BooleanField(default='True'),
        ),
    ]
