# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171213_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='owner',
        ),
    ]
