# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_table_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(default='#fff9ac', max_length=10),
        ),
    ]
