# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_card_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='private_access',
        ),
        migrations.AddField(
            model_name='board',
            name='public_access',
            field=models.BooleanField(default=False),
        ),
    ]
