# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171109_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardTitle', models.TextField(max_length=50, unique=True)),
                ('boardDescription', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
