# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='boardID',
            new_name='tableID',
        ),
    ]
