# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171109_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='boardID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Board'),
            preserve_default=False,
        ),
    ]
