# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_table_boardid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='status',
            new_name='archiveStatus',
        ),
    ]
